config/routes.rb
Olac::Application.routes.draw do
  root :to => 'home#index'

 #root  get "home/index"

  get "assets/index", :as => :ember

  resources :records
  resources :notes
  resources :annotations
  resources :comments
  
  get "review", to: "review#index"
  post "review", to: "review#search"
  
end

app/models/annotation.rb
class Annotation
  include Mongoid::Document
  include Mongoid::Timestamps
  
#  validates :role_language, :presence => { :message => "The language field cannot be blank." }
  scope :need_approval, where( :approved == true )
  
  field :name, type: String
  field :canonical_name, type: String
  field :role, type: String
  field :role_translation, :type => String
  field :role_language, :type => String
  field :approved, :type => Boolean, :default => true 
  field :comment

  embedded_in :note

  def note_id=(id)
     self.note = Note.find_by(:id => id)
  end


end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MagicCounterCache
  
  
  field :text, type: String
  field :commentersName, type: String
  
  belongs_to :note
  
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MagicCounterCache
  
  
  field :text, type: String
  field :language, type: String # this is the lang from the filename
  field :marc_language, type: String # this is lang from the 008 field
  
  field :input_field, type: String
  field :record_title, type: String
  
  
  
  field :approved_counter, :type => Integer, :default => 0
  field :needs_approved_counter, :type => Integer, :default => 0
  
  index({ language: 1 }, { unique: false })
  index 'annotations.role_language' => 1  
  belongs_to :record
  embeds_many :annotations
  embeds_many :comments
  
  attr_accessor :randomized
  
  def authority_names
    record.authority_names
  end
  
  scope :needs_approval, where(:needs_approved_counter.gt => 0 ).order_by(:need_approved_counter => :asc)
  scope :annotated, where(:approved_counter.gt => 0).order_by(:updated_at => :desc )  

  
  def update_approved_counter
    self.approved_counter += 1
    self
  end
  
  protected
  

  
  
  # When we are in annotation mode, we want a random record without an annotations. 
  def self.get_random_by_language(language)
    records = Note.where(language: language, :approved_counter.lt => 2)
    cnt = ( records.count - 1 ) 
    offset = rand(cnt)
    records.skip(offset).limit(1).map { |r| r.randomized = true; r }
  end
  
  
  
  
end

app/models/record.rb
class Record
  include Mongoid::Document
    
  field :marc_hash, type: Hash
  field :title, type: String
  field :record_id, type: String
  field :language, :type => String

  field :authority_names, :type => Array
  before_validation :set_authority_names

  has_many :notes
  
  index({ language: 1 }, { unique: false })
  
  protected
  
  def set_authority_names
     unless self.marc_hash.nil?
        results = []
        marc = MARC::Record.new_from_marchash(self.marc_hash)
        [ "100", "700"].each do |field|
           marc.fields(field).each_with_index do |str, index|
               results << { :name => str["a"].chomp("."), :field => "#{field}-00#{index.to_s}", :record_id => self.record_id }
           end
        end

        [ "110", "710"].each do |field|
            marc.fields(field).each_with_index do |str, index|
              if str['a']
                name = "#{str['a'].chomp('.')}"
                name << " -- #{str['b'].chomp('.')}" if str['b']
                results << { :name => name, :field => "#{field}-00#{index.to_s}", :record_id => self.record_id }
              end
            end
         end

        self.authority_names = results.sort_by { |r| r[:name] }
     end
  end
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  respond_to :json

  def create
    a = Annotation.create(annotation_params)
    respond_with a, status: :ok
  end
  
  private
  
  def annotation_params
    params.require(:annotation).permit(:name, :canonical_name, :role, :role_translation, :role_language, :comment, :note_id, :approved )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json

  def create
    comment = Comment.create(comment_params)
    respond_with comment, status: :ok   
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:text, :commentersName, :note_id )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  respond_to :json
  
  
  def index
    if params[:random] == "true"
      respond_with Note.get_random_by_language(params[:language])
    elsif params[:ids]
      respond_with Note.where(:_id.in => params[:ids]).all.to_a
    else
      respond_with Note.limit(5)
    end
   end
  
  # all this needs to do is update the approved counter that we're pushing a session.
  def update
    note = Note.find(params[:id])
    note.approved_counter += 1
    respond_with note.save
   end
  
  def show
    respond_with Note.find(params[:id])
  end
  
  private
  

  
  
end

app/controllers/review_controller.rb
require 'csv'
class ReviewController < ApplicationController

  
  def index
      respond_to do |format|
         format.html { render layout: 'review' }
       end
  end


  def search
    params[:page] ||= 1
    params[:per_page] ||= 20
    
    @notes =  Note.annotated.paginate(:page => params[:page], :per_page => params[:per_page])
    
    anno = @notes.collect { |n| n.annotations }
    @annotations = anno.flatten
    
    @csv = ""
    @csv << ["marc_record id", "marc_language", "note id", 'annotation id', 'creation date', "record title", "record language",  "credit", "annotated role language", "annotated name", 'annotated canonical name',  "annotated role", "annotated role translation", "approved", "note's number of approved annotations", "comment" ].to_csv
    @annotations.each do |annotation| 
      marc_lang = annotation.note.marc_language
      marc_id = annotation.note.record.record_id 
      @csv << [marc_id,marc_lang, annotation.note.id , annotation.id, annotation.attributes['created_at'], annotation.note.record_title, annotation.note.language, annotation.note.text, annotation.role_language, annotation.name,
         annotation.canonical_name, annotation.role, annotation.role_translation, annotation.approved?, annotation.note.approved_counter, annotation.comment ].map { |c| c.to_s.encode("UTF-8") }.to_csv
    end  
    
     respond_to do |format|
       format.csv { render text: @csv }
       #format.html { render layout: false }
     end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
   <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lean Canvas" %>">

  <title><%= content_for?(:title) ? yield(:title) : "OLAC Movie & Video Credit Annotation Experiment" %></title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/review.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
   <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lean Canvas" %>">

  <title><%= content_for?(:title) ? yield(:title) : "OLAC" %></title>
  <%= javascript_include_tag "review" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/review/index.html.erb
<%= form_tag( review_path(format: 'csv' ), method: "search",  class: 'form-horizontal'  ) do %>
   <div class="control-group">
      <%= label_tag(:per_page, "Number Of Records:", class: "control-label" ) %>
      <div class="controls">
        <%= text_field_tag(:per_page,  100) %>
      </div>
    </div>
     <div class="control-group">
        <%= label_tag(:page, "Page Offset:", class: "control-label" ) %>
        <div class="controls">
          <%= text_field_tag(:page, 1) %>
        </div>
      </div>
  <%= submit_tag("Review Annotations") %>
<% end %>

app/views/review/search.text.erb
<%= @csv %>